### ISSUE TITLE
Wish:  Hardware/README

### ISSUE THREAD

**Issue by stappersg** [clydeshaffer/gametank#4]
I think it would be a good thing if the `Hardware` directory gets a _README_ file.

The improvement that I see is that the _README_ tells what the _next toplevel_ is and with which tooling the files should be viewed (and/or modified).

**Comment by clydeshaffer** [comment]
Makes sense to me! I'll whip up a file that explains the directory structure.

**Comment by clydeshaffer** [comment]
@stappersg I just added a README there, let me know if it explains clearly enough

**Comment by stappersg** [comment]
Commit https://github.com/clydeshaffer/gametank/commit/736e3caa47b7d2902423b875f25a3ee244a5e97b is indeed the improvement I was aiming for.
